name: 'GCP GitHub Secrets'
description: 'Fetch secrets from GCP Secret Manager using GitHub Actions OIDC'
inputs:
  workload_identity_provider:
    description: 'The full workload identity provider resource name'
    required: true
  secrets:
    description: 'Newline-separated list of secrets to fetch in format: SECRET_NAME:output_name or just SECRET_NAME'
    required: true
  project_id:
    description: 'GCP project ID (optional if secrets are fully qualified)'
    required: false
outputs:
  # Outputs are dynamic based on the secrets requested
  # Each secret will be available as an output with the specified output_name
runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Fetch secrets
      shell: bash
      id: fetch
      env:
        SECRETS_INPUT: ${{ inputs.secrets }}
        PROJECT_ID: ${{ inputs.project_id }}
      run: |
        while IFS= read -r line; do
          # Skip empty lines
          [[ -z "$line" ]] && continue

          # Parse SECRET_NAME:output_name or just SECRET_NAME
          if [[ "$line" == *":"* ]]; then
            secret_name="${line%%:*}"
            output_name="${line##*:}"
          else
            secret_name="$line"
            output_name="$line"
          fi

          # Fetch the secret
          if [[ -n "$PROJECT_ID" ]]; then
            secret_value=$(gcloud secrets versions access latest --secret="$secret_name" --project="$PROJECT_ID")
          else
            secret_value=$(gcloud secrets versions access latest --secret="$secret_name")
          fi

          # Mask the secret value in logs
          echo "::add-mask::$secret_value"

          # Set as output (handle multiline secrets)
          {
            echo "${output_name}<<EOF"
            echo "$secret_value"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          echo "Fetched secret: $secret_name -> $output_name"
        done <<< "$SECRETS_INPUT"
